<?php include("../header.php") ?>
<script>
	document.getElementById("title").innerHTML="General Fees and Charges | AFTT";
</script>
<!-- banner -->
		<div class="container-fluid maket_header" style="background-color: #111827;">
		  <div class="container ">
				<div class="row text-white">
					<div class="col-sm-12 p_center" >
						<h1 class="mb-3 mt-5">General Fees and Charges</h1>
						<h5>Our fees are fully transparent so you always know the cost of trading and investing through us.</h5>
												
					</div>
					
				</div>
			</div>
		</div>

<div class="container-fluid" style="background: #f3f4f6;overflow: hidden;">
	<div class="container maket_header">
		<div class="row">	
				<div class="col-12 pb-4">
					<h2 class="mb-3">Financing Details</h2>
					<h6>The fees shown on the webpage apply to new clients only. Existing clients should refer to the latest details on the trading platform.<h6>
				</div>
				<div class="col-12">
					<div class="accordion specification_card" id="accordionExample2">
						  <div class="card">
							<div class="card-header" id="help_h_02_01">
							  <h2 class="mb-0">
								<button class="btn btn-link" type="button" data-toggle="collapse" data-target="#help_02_01" aria-expanded="true" aria-controls="help_02_01">
								  Margin Product Financing Rates
								</button>
							  </h2>
							</div>
							<div id="help_02_01" class="collapse show" aria-labelledby="help_h_02_01" data-parent="#accordionExample2">
							  <div class="card-body ">
								<p>To help you achieve your financial goals and trading objectives, we provide funding and liquidity support for your margin product trading activities. When you hold an overnight position in a margin product (such as a single stock CFD), you will need to pay a financing rate.
								</p><p>
								Your financing rate consists of two parts: 1) AFTT buy/sell financing rate and 2) the rate markup/markdown for the commercial product.
								</p><p>
								Financing rates are set as follows:<br>
									Buy = AFTT buy financing rate - Rate markdown for the commercial product
								<br>Sell = AFTT sell financing rate + Rate markup for the commercial product
								</p><p>
								AFTT Buy/Sell Financing Rates
								<br>The AFTT buy/sell financing rate refers to our pricing for financing, i.e., the charge for floating interest. When setting the AFTT buy/sell financing rate, we use Alternative Reference Rates (ARR) as input. If a currency does not have a designated Alternative Reference Rate, a money market rate, policy rate, or other relevant financial benchmark is used instead.
								<br>The minimum AFTT buy/sell financing rate is zero, meaning interest cannot be negative.
								</p><p>
								When buying a single stock CFD in HKD, we will convert the funding base to HKD to finance the purchase activity for that stock. Conversely, when selling a single stock CFD in ZAR, we will convert the proceeds from the sold stock into our funding base currency. These operations require active trading of different financial products in the interbank market to manage the liquidity flows generated by your trading activities.
								</p><p>
								Alternative Reference Rates are developed by working groups, which include domestic and international industry associations, market participants, and central banks. They are publicly available benchmark rates, recognized by National Competent Authorities (NCA), market participants, and domestic and international financial industry associations. For more information on the relevant financial benchmarks listed below, please consult the financial benchmark administrator, central banks, or reserve banks.
								</p><p>
								The AFTT buy/sell financing rate is proprietary to AFTT and is governed by the General Business Terms. One clause relates to cost pass-through associated with external factors, such as changes in domestic and/or international monetary or credit policies affecting overall interest levels, or changes in the cost structure of liquidity providers and brokers.
								</p><p>
								For reference, please see the applicable benchmark rates listed below.
								Rate Markup/Markdown for the Commercial Product
								</p><p>
								For more information on our general pricing, please visit the pricing overview page.
								</p><p>
								Interest Calculation and Settlement
								<br>
								We calculate your interest daily and settle it within seven business days of the end of each calendar month.</p>
							  </div>
							</div>
						  </div>
						  <div class="card">
							<div class="card-header" id="help_h_02_02">
							  <h2 class="mb-0">
								<button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#help_02_02" aria-expanded="false" aria-controls="help_02_02">
								  AFTT Sell/Buy Interest
								</button>
							  </h2>
							</div>
							<div id="help_02_02" class="collapse" aria-labelledby="help_h_02_02" data-parent="#accordionExample2">
							  <div class="card-body ">
								<p>The AFTT sell/buy interest rate is proprietary to AFTT and is governed by the General Business Terms. One clause relates to cost pass-through associated with external factors, such as changes in domestic and/or international monetary or credit policies affecting overall interest levels, or changes in the cost structure of liquidity providers and brokers.
								</p><p>
								When setting the AFTT sell/buy interest rate, we typically use Alternative Reference Rates (ARR) as input. For some currencies, a money market rate, policy rate, or other relevant financial benchmark is used instead.
								</p><p>
								The table below lists the benchmarks used when setting deposit rates and financing rates for margin products. AFTT reserves the right to delay the adoption of published financial benchmarks in the business when calculating and recording unrealized and realized interest.</p>
								<table cellpadding="0" cellspacing="0" class="table table-striped"><thead class="thead-dark" ><tr><th class="v2-table__highlight--col"><strong>Currency</strong></th><th><strong>Day Count Convention</strong></th><th><strong>Benchmark Rate</strong></th></tr></thead><tbody><tr><td class="v2-table__highlight--col"><strong>AED</strong></td><td>ACT/360</td><td>Central Bank of United Arab Emirates (CBUAE) repo rate</td></tr><tr><td class="v2-table__highlight--col"><strong>AUD</strong></td><td>ACT/365</td><td>Australian Overnight Index Average (AONIA)</td></tr><tr><td class="v2-table__highlight--col"><strong>CAD</strong></td><td>ACT/365</td><td>Canadian Overnight Repo Rate Average (CORRA)</td></tr><tr><td class="v2-table__highlight--col"><strong>CHF</strong></td><td>ACT/360</td><td>Swiss Average Rate Overnight (SARON)</td></tr><tr><td class="v2-table__highlight--col"><strong>CNH</strong></td><td>ACT/360</td><td>CNH China InterBank Repo</td></tr><tr><td class="v2-table__highlight--col"><strong>CZK</strong></td><td>ACT/360</td><td>Czech Overnight Index Average (CZEONIA)</td></tr><tr><td class="v2-table__highlight--col"><strong>DKK</strong></td><td>ACT/360</td><td>Denmark Short-Term Rate (DESTR) or Current-account rate</td></tr><tr><td class="v2-table__highlight--col"><strong>EUR</strong></td><td>ACT/360</td><td>Euro Short-Term Rate (ESTR)</td></tr><tr><td class="v2-table__highlight--col"><strong>GBP</strong></td><td>ACT/365</td><td>Sterling Overnight Index Average (SONIA)</td></tr><tr><td class="v2-table__highlight--col"><strong>HKD</strong></td><td>ACT/365</td><td>HKD Overnight Deposit rate</td></tr><tr><td class="v2-table__highlight--col"><strong>HUF</strong></td><td>ACT/360</td><td>Hungarian Overnight Index Average (HUFONIA)</td></tr><tr><td class="v2-table__highlight--col"><strong>ILS</strong></td><td>ACT/360</td><td>Bank of Israel (BoI) rate</td></tr><tr><td class="v2-table__highlight--col"><strong>JPY</strong></td><td>ACT/360</td><td>Tokyo Overnight Average Rate (TONAR)</td></tr><tr><td class="v2-table__highlight--col"><strong>MXN</strong></td><td>ACT/360</td><td>Overnight TIIE funding rate</td></tr><tr><td class="v2-table__highlight--col"><strong>NOK</strong></td><td>ACT/360</td><td>Norwegian Overnight Weighted Average (NOWA)</td></tr><tr><td class="v2-table__highlight--col"><strong>NZD</strong></td><td>ACT/365</td><td>Reserve Bank of New Zealand (RBNZ) Official Cash Rate (OCR)</td></tr><tr><td class="v2-table__highlight--col"><strong>PLN</strong></td><td>ACT/360</td><td>Poland Overnight Index Average (POLONIA)</td></tr><tr><td class="v2-table__highlight--col"><strong>RON</strong></td><td>ACT/360</td><td>National Bank of Romania deposit rate</td></tr><tr><td class="v2-table__highlight--col"><strong>RUB</strong></td><td>ACT/360</td><td>Ruble Overnight Index Average (RUONIA)</td></tr><tr><td class="v2-table__highlight--col"><strong>SAR</strong></td><td>ACT/360</td><td>Central Bank of Saudi Arabia (SAMA) reverse repo rate</td></tr><tr><td class="v2-table__highlight--col"><strong>SEK</strong></td><td>ACT/360</td><td>Swedish Short-Term Rate (SWESTR)</td></tr><tr><td class="v2-table__highlight--col"><strong>SGD</strong></td><td>ACT/365</td><td>Singapore Overnight Rate Average (SORA)</td></tr><tr><td class="v2-table__highlight--col"><strong>THB</strong></td><td>ACT/365</td><td>Thai Overnight Rate (THOR)</td></tr><tr><td class="v2-table__highlight--col"><strong>TRY</strong></td><td>ACT/360</td><td>Turkish Lira Reference Rate (TLREF)</td></tr><tr><td class="v2-table__highlight--col"><strong>USD</strong></td><td>ACT/360</td><td>Secured Overnight Financing Rate (SOFR)</td></tr><tr><td class="v2-table__highlight--col"><strong>ZAR</strong></td><td>ACT/365</td><td>South Africa Benchmark Overnight Rate (SABOR)</td></tr></tbody></table>							
							  </div>
							</div>
						  </div>
						  <div class="card">
							<div class="card-header" id="help_h_02_03">
							  <h2 class="mb-0">
								<button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#help_02_03" aria-expanded="false" aria-controls="help_02_03">
								  Currency Conversion Fee
								</button>
							  </h2>
							</div>
							<div id="help_02_03" class="collapse" aria-labelledby="help_h_02_03" data-parent="#accordionExample2">
							  <div class="card-body ">
								<p>When the currency of the financial instrument you are trading differs from your account currency — including realized profit and loss — the transaction will be converted using the forex spot mid-rate at the time of closing the position, plus/minus 0.25%. Our currency conversion fee does not exceed plus/minus 0.25%.
								</p><p>Currency conversion fees do not apply to margin collateral and only include actual payment settlement on the trading account, such as buying/selling cash stocks, paying/receiving option premiums, etc.
								</p><p>The exchange rate used to convert amounts in your account will be displayed in the "Executed Trades" report on the trading platform.</p>
								
							  </div>
							</div>
						  </div>
						  <div class="card">
							<div class="card-header" id="help_h_02_04">
							  <h2 class="mb-0">
								<button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#help_02_04" aria-expanded="false" aria-controls="help_02_04">
								  Report Fee
								</button>
							  </h2>
							</div>
							<div id="help_02_04" class="collapse" aria-labelledby="help_h_02_04" data-parent="#accordionExample2">
							  <div class="card-body ">
								<p>Clients on the Basic Service level requesting reports via standard mail or email that are already available online will be charged $50 or the equivalent in the account currency. This fee will also apply to reports requested by third parties, such as auditor reports.</p>
								
							  </div>
							</div>
						  </div>
						  <div class="card">
							<div class="card-header" id="help_h_02_05">
							  <h2 class="mb-0">
								<button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#help_02_05" aria-expanded="false" aria-controls="help_02_05">
								  Manual Order Fee
								</button>
							  </h2>
							</div>
							<div id="help_02_05" class="collapse" aria-labelledby="help_h_02_05" data-parent="#accordionExample2">
							  <div class="card-body ">
								<p>Clients placing orders via phone, chat, or email will be charged a manual order fee of €50 per order. Certain products not available for trading on the platform may be exempt from this fee.</p>
								
							  </div>
							</div>
						  </div>
						  <div class="card">
							<div class="card-header" id="help_h_02_55">
							  <h2 class="mb-0">
								<button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#help_h_02_55" aria-expanded="false" aria-controls="help_h_02_55">
								  Form 1042-S Fee
								</button>
							  </h2>
							</div>
							<div id="help_02_05" class="collapse" aria-labelledby="help_h_02_55" data-parent="#accordionExample2">
							  <div class="card-body ">
								<p>You can request a Form 1042-S, but you must meet at least one of the following conditions, or a €1,000 fee per income year will apply:
								</p><p>
									You can provide proof that the IRS requires you to submit Form 1042-S.<br>
									AFTT applied an incorrect US tax withholding rate to your account.
								</p><p>
								If you request more than 10 forms per income year, the fee will exceed €1,000 per year.</p>
								
							  </div>
							</div>
						  </div>
						  <div class="card">
							<div class="card-header" id="help_h_02_06">
							  <h2 class="mb-0">
								<button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#help_02_06" aria-expanded="false" aria-controls="help_02_06">
								  Proxy Voting Service Fee
								</button>
							  </h2>
							</div>
							<div id="help_02_06" class="collapse" aria-labelledby="help_h_02_06" data-parent="#accordionExample2">
							  <div class="card-body ">
								<p>We charge a proxy voting service fee for clients subscribed to AFTT Bank’s Meeting Services. Additionally, a voting fee will be charged for each vote or vote change.</p>
								<table class="table"><thead><tr><th><strong>Description</strong></th><th><strong>Fee</strong></th></tr></thead><tbody><tr><td>Service Subscription<br></td><td>€30 per year (excluding VAT)</td></tr><tr><td>Vote/Change Vote<br></td><td>€5 per vote (excluding VAT)</td></tr></tbody></table>
								<p>The service subscription fee will be charged at the end of each quarter and is non-refundable. If you subscribe and unsubscribe from the service within the same quarter, the full fee will be charged. Where applicable, the service subscription fee will be converted to the applicable local currency and subject to currency conversion fees. The first subscription fee will be charged at the end of Q4 2020, and no subscription fee will be charged for Q3 2020.
								</p><p>The voting fee will be charged at the time of voting. Where applicable, the voting fee will be converted to the applicable local currency and subject to currency conversion fees. The voting fee will be charged starting from September 3, 2020, with the first charge at the end of Q4 2020.</p>
							  </div>
							</div>
						  </div>
						  <div class="card">
							<div class="card-header" id="help_h_02_07">
							  <h2 class="mb-0">
								<button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#help_02_07" aria-expanded="false" aria-controls="help_02_07">
								  Fee for Adding Investment Products on the Platform
								</button>
							  </h2>
							</div>
							<div id="help_02_07" class="collapse" aria-labelledby="help_h_02_07" data-parent="#accordionExample2">
							  <div class="card-body ">
								<p>Please note that Basic and Platinum accounts will be charged a $200 fee for each new product added; VIP clients can add investment products for free. The fee will only be charged once the investment product is successfully added. To check your current account level, please go to the "Account" page on the platform and then select "AFTT Points".</p>
							  </div>
							</div>
						  </div>
						  
						  
						  
						</div>
				</div>
				
			</div>
	</div>
</div>
<div class="container-fluid" style="background: #f3f4f6;">
		
	<div class="container maket_header pt-0 products_p">
		<div class="row">
			<div class="col-sm-12 mb-4">
				<h2>See All Our Prices</h2>
			</div>
			<div class="col-lg-3 col-md-4 col-6">
				<a href="/rates-and-conditions/forex.php" class="pricie_bg">
					<p class="fwb mb-3">Forex</p>
					<p class=" ">Spreads from</p>
					<h1>0.4 <span class="h3"> pips</span></h1>
					<p class="pricie_cont">Trade 185 forex spot pairs and 140 forwards, plus spot metals, with no commission fees.</p>
					<p class="blue fwb mb-0">See All Prices</p>
				</a>
			</div>
			<div class="col-lg-3 col-md-4 col-6">
				<a href="/rates-and-conditions/forex-options.php" class="pricie_bg">
					<p class="fwb mb-3">Forex Options</p>
					<p class=" ">Spreads from</p>
					<h1>3 <span class="h3"> pips</span></h1>
					<p class="pricie_cont">Trade 45 vanilla forex options with expiries from one day to 12 months.</p>
					<p class="blue fwb mb-0">See All Prices</p>
				</a>
			</div>
			<div class="col-lg-3 col-md-4 col-6">
				<a href="/rates-and-conditions/stocks.php" class="pricie_bg">
					<p class="fwb mb-3">Stocks</p>
					<p class=" ">US stock commissions from</p>
					<h1>$1 <span class="h3"> </span></h1>
					<p class="pricie_cont">Trade over 23,500 stocks across 50 exchanges worldwide in core and emerging markets.</p>
					<p class="blue fwb mb-0">See All Prices</p>
				</a>
			</div>
			<div class="col-lg-3 col-md-4 col-6">
				<a href="/rates-and-conditions/etf.php" class="pricie_bg">
					<p class="fwb mb-3">ETFs</p>
					<p class=" ">US-listed ETF commissions from</p>
					<h1>$1 <span class="h3"> </span></h1>
					<p class="pricie_cont">Trade over 7,000 ETFs from more than 30 exchanges worldwide.</p>
					<p class="blue fwb mb-0">See All Prices</p>
				</a>
			</div>
			<div class="col-lg-3 col-md-4 col-6">
				<a href="/rates-and-conditions/futures.php" class="pricie_bg">
					<p class="fwb mb-3">Futures</p>
					<p class=" ">Commissions from per lot</p>
					<h1>$1 <span class="h3"> </span></h1>
					<p class="pricie_cont">Trade over 250 futures, including stock indices, energy, metals, agriculture, interest rates, and forex.</p>
					<p class="blue fwb mb-0">See All Prices</p>
				</a>
			</div>
			<div class="col-lg-3 col-md-4 col-6">
				<a href="/rates-and-conditions/bonds.php" class="pricie_bg">
					<p class="fwb mb-3">Bonds</p>
					<p class=" ">Government bond commissions from</p>
					<h1>0.05% <span class="h3"> </span></h1>
					<p class="pricie_cont">Trade government bonds online or offline across 26 countries/regions and 21 types.</p>
					<p class="blue fwb mb-0">See All Prices</p>
				</a>
			</div>
			<div class="col-lg-3 col-md-4 col-6">
				<a href="/rates-and-conditions/listed-options.php" class="pricie_bg">
					<p class="fwb mb-3">Listed Options</p>
					<p class=" ">Commissions from per lot</p>
					<h1>$0.75 <span class="h3"> </span></h1>
					<p class="pricie_cont">Trade over 3,200 listed options on stocks, energy, and metals from 20 exchanges worldwide.</p>
					<p class="blue fwb mb-0">See All Prices</p>
				</a>
			</div>
			<div class="col-lg-3 col-md-4 col-6">
				<a href="/products/mutual-funds.php" class="pricie_bg">
					<p class="fwb mb-3">Mutual Funds</p>
					<p class=" ">Commission, custody, and platform fees from</p>
					<h1>$0 <span class="h3"> </span></h1>
					<p class="pricie_cont">Access over 500 top mutual funds through the world's largest investors.</p>
					<p class="blue fwb mb-0">See All Prices</p>
				</a>
			</div>
			<div class="col-lg-3 col-md-4 col-6">
				<a href="/products/ipo.php" class="pricie_bg">
					<p class="fwb mb-3">IPO</p>
					<p class=" ">Financing rates from</p>
					<h1>0% <span class="h3"> </span></h1>
					<p class="pricie_cont">Enjoy up to 10x leverage and low handling fees when subscribing to newly issued stocks listed on the HKEx.</p>
					<p class="blue fwb mb-0">See All Prices</p>
				</a>
			</div>
			<div class="col-lg-3 col-md-4 col-6">
				<a href="/rates-and-conditions/commodities.php" class="pricie_bg">
					<p class="fwb mb-3">Commodities</p>
					<p class=" ">Commissions from</p>
					<h1>$0.85 <span class="h3"> per lot</span></h1>
					<p class="pricie_cont">Trade various commodities like CFDs, futures, options, and spot pairs.</p>
					<p class="blue fwb mb-0">See All Prices</p>
				</a>
			</div>
		</div>
	</div>
	
</div>
<div class="container-fluid text-white" style="background: #0d1017;">
	<div class="container maket_header">
		<div class="row text-center ">
			<div class="col-sm-12">
				<h2 class="mb-1">Ready to Get Started?</h2>	
				<h5>Opening an account takes about 5 minutes</h5>				
			</div>			
			
			<div class="col-sm-12">
				<div class="pt-4">											
					<a href="https://login.aftt-portal.com/register/trader" class="btn btn-primary"><strong>Open Account</strong></a>
				</div>
			</div>
		</div>
	</div>
</div>
<?php include("../footer.php") ?>
<script type="text/javascript">
$('.app_ys li').click(function() {
        $(this).siblings('li').removeClass('active');
        $(this).addClass('active');    
});
$(document).ready(function() {
  $('.app_ys li').click(function() {
    var index = $(this).index(); // 获取悬停的li的索引
    $('#image-viewer img').hide(); // 先隐藏所有的图片
    $('#image-viewer img').eq(index).show(); // 显示对应索引的图片
  });
});
</script>
